project_demo_web_goi_y_phim/Movie-Recommendation-App/MRS/urls.py
from django.contrib import admin
from django.urls import path
from MovieRecommender import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/',views.signup,name="signup"),
    path('login/',views.user_login,name="login"),
    path('home/',views.home,name="home"),
    path('dashboard/',views.dashboard,name="dashboard"),
    path("addmovie/",views.addmovie,name="addmovie"),
    path("logout/",views.user_logout,name="logout"),
    path("profile/",views.profile,name="profile")
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

project_demo_web_goi_y_phim/Movie-Recommendation-App/MovieRecommender/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Movie(models.Model):
    title=models.CharField(max_length=70)
    genres=models.CharField(max_length=70)
    year=models.CharField(max_length=70)
    image=models.ImageField(upload_to="movie_image")
    movieduration=models.CharField(max_length=70)
    def __str__(self):
        return str(self.pk)
    
    def get_total_ratings(self):
        total_ratings = self.rating_set.count()
        return total_ratings
    
    def get_average_rating(self):
        average_rating = self.rating_set.aggregate(avg_rating=models.Avg('rating'))
        avg = average_rating['avg_rating']
        if avg is not None:
            rounded_avg = round(avg, 2)
            return rounded_avg
        return None
class Rating(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,default=None)
    movie=models.ForeignKey(Movie,on_delete=models.CASCADE,default=None)
    rating=models.CharField(max_length=70)
    rated_date=models.DateTimeField(auto_now_add=True)

project_demo_web_goi_y_phim/Movie-Recommendation-App/MovieRecommender/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Movie,Rating
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
class SignUpForm(UserCreationForm):
    password1=forms.CharField(label='Password',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2=forms.CharField(label='Confirm Password',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model=User
        fields=['username','first_name','last_name','email']
        labels={'first_name':'First Name','last_name':'Last Name','email':'Email Address'}
        widgets={
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'first_name':forms.TextInput(attrs={'class':'form-control'}),
            'last_name':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}),
        }

class AddMovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields='__all__'
        labels={'title':'Movie Title','image':'','movieduration':'Duration'}
        widgets={
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'genres':forms.TextInput(attrs={'class':'form-control'}),
            'year':forms.TextInput(attrs={'class':'form-control'}),
            'image':forms.FileInput(attrs={'class':'form-control'}),
            'movieduration':forms.TextInput(attrs={'class':'form-control'})
        }

class LoginForm(AuthenticationForm):
    username=forms.CharField(label='Username',widget=forms.TextInput(attrs={'class':'form-control'}))
    password=forms.CharField(label='Password',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        fields=['username','password']


class AddRatingForm(forms.ModelForm):
  
    class Meta:
        model=Rating
        fields=['rating']
        labels={'rating':'Rating'}
        widgets={
            'rating':forms.TextInput(attrs={'type':'range','step':'1','min':'0','max':'5','class':{'custom-range','border-0'}})
        }

project_demo_web_goi_y_phim/Movie-Recommendation-App/MovieRecommender/views.py
from django.shortcuts import render,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout,update_session_auth_hash
from django.contrib.auth.models import User,Group
from .forms import SignUpForm,AddMovieForm,LoginForm,AddRatingForm
from .models import Movie,Rating
from django.contrib import messages
import pandas as pd
from math import sqrt
import numpy as np
import matplotlib.pyplot as plt
from math import ceil
from surprise import KNNBasic
import heapq
from collections import defaultdict
from operator import itemgetter
from surprise import Dataset
from surprise import Reader
from django.utils import timezone

# Create your views here.

def filterMovieByGenre():
     #filtering by genres
    allMovies=[]
    genresMovie= Movie.objects.values('genres', 'id')
    genres= {item["genres"] for item in genresMovie}
    for genre in genres:
        movie=Movie.objects.filter(genres=genre)
        print(movie)
        n = len(movie)
        nSlides = n // 4 + ceil((n / 4) - (n // 4))
        allMovies.append([movie, range(1, nSlides), nSlides])
    params={'allMovies':allMovies }
    return params


def generateRecommendation(request):
    if request.user.is_authenticated:
        movie=Movie.objects.all()
        rating=Rating.objects.all()
        x=[] 
        y=[]
        A=[]
        B=[]
       
        #Rating Data Frames
        # print(rating)
        for item in rating:
            A=[item.user.id,item.movie,item.rating]
            B+=[A]
        rating_df=pd.DataFrame(B,columns=['userId','movieId','rating'])
        testSubject = request.user.id
        k = 10

        reader = Reader(rating_scale=(1, 5))  # Adjust the rating scale as per your dataset
        data = Dataset.load_from_df(rating_df[['userId', 'movieId', 'rating']], reader)
        trainSet = data.build_full_trainset()
        print("This is Train Set")
        # print(trainSet)
        sim_options = {'name': 'cosine',
                    'user_based': False
                    }

        model = KNNBasic(sim_options=sim_options)
        # print("This is model")
        # print(model)
        model.fit(trainSet)
        simsMatrix = model.compute_similarities()
        
        print(simsMatrix)
        testUserInnerID = trainSet.to_inner_uid(testSubject)
        print(testUserInnerID)
        # Get the top K items we rated
        testUserRatings = trainSet.ur[testUserInnerID]
        kNeighbors = heapq.nlargest(k, testUserRatings, key=lambda t: t[1])

        # Get similar items to stuff we liked (weighted by rating)
        candidates = defaultdict(float)

        candidates2 = defaultdict(float)
        for itemID, rating in kNeighbors:
            similarityRow = simsMatrix[itemID]
            
            for innerID, score in enumerate(similarityRow):
            
                candidates[innerID] += score * rating
                candidates2[innerID] += score 
                
        for itemID, ratingSum in sorted(candidates.items(), key=itemgetter(1), reverse=True):
            
            if candidates2[itemID] != 0:
                    candidates[itemID] = candidates[itemID] / candidates2[itemID]
            else:
                    candidates[itemID] = 0  # or handle the zero division case as per your requirement

            
                
            
        # Build a dictionary of stuff the user has already seen
        watched = {}
        for itemID, rating in trainSet.ur[testUserInnerID]:
            watched[itemID] = 1
        print(watched)    
        # Get top-rated items from similar users:
        movie_ids = [] 
        pos = 0
        for itemID, ratingSum in sorted(candidates.items(), key=itemgetter(1), reverse=True):
            
            if not itemID in watched:
                movieID = trainSet.to_raw_iid(itemID)
                movie_ids.append(movieID)
                print(movieID, ratingSum)
                pos += 1
                if (pos > 10):
                    break

        
       
        print(movie_ids)
        for item in movie: 
            if any(item.id == movie_obj.id for movie_obj in movie_ids):
                x=[item.id,item.title,item.movieduration,item.genres] 
                y+=[x]
        movies_df = pd.DataFrame(y,columns=['movieId','title','movieduration','genres'])
        
        recommender = movies_df
        print("We recommend:")
        print(movies_df)


       
       
        return recommender.to_dict('records')
            

            




def signup(request):
    if not request.user.is_authenticated:
        if request.method=='POST':
            fm=SignUpForm(request.POST)
            if fm.is_valid():
                user=fm.save()
                group=Group.objects.get(name='Editor')
                user.groups.add(group)
                messages.success(request,'Account Created Successfully!!!')
        else:
            if not request.user.is_authenticated:
                fm=SignUpForm()
        return render(request,'MovieRecommender/signup.html',{'form':fm})
    else:
        return HttpResponseRedirect('/home/')

def user_login(request):
    if not request.user.is_authenticated:
        if request.method=='POST':
            fm=LoginForm(request=request,data=request.POST)
            if fm.is_valid():
                uname=fm.cleaned_data['username']
                upass=fm.cleaned_data['password']
                user=authenticate(username=uname,password=upass)
                if user is not None:
                    login(request,user)
                    messages.success(request,'Logged in Successfully!!')
                    return HttpResponseRedirect('/dashboard/')
        else:
            fm=LoginForm()
        return render(request,'MovieRecommender/login.html',{'form':fm})
    else:
        return HttpResponseRedirect('/dashboard/')



def home(request):
    params=filterMovieByGenre()
    params['recommended']=generateRecommendation(request)
    return render(request,'MovieRecommender/home.html',params)

def addmovie(request):
    if request.user.is_authenticated:
        if request.method=='POST':
            fm=AddMovieForm(request.POST,request.FILES)
            if fm.is_valid():
                fm.save()
                messages.success(request,'Movie Added Successfully!!!')
        else:
            fm=AddMovieForm()
        return render(request,'MovieRecommender/addmovie.html',{'form':fm})
    else:
        return HttpResponseRedirect('/login/')


def dashboard(request):
    if request.user.is_authenticated: 
        params=filterMovieByGenre()
        params['user']=request.user
        params['watchedMovie'] = movie_watched(request)
        if request.method=='POST':
            userid=request.POST.get('userid')
            movieid=request.POST.get('movieid')
            movie=Movie.objects.all()
            u=User.objects.get(pk=userid)
            m=Movie.objects.get(pk=movieid)
            rfm=AddRatingForm(request.POST)
            params['rform']=rfm
            if rfm.is_valid():
                rat=rfm.cleaned_data['rating']
                count=Rating.objects.filter(user=u,movie=m).count()
                ratingInDb = Rating.objects.filter(user=u, movie=m).first()
                # Retrieve all movies for the specific user
                # moviesOfUser = Movie.objects.filter(rating__user=u)
                # print("watched movie")
                # print(moviesOfUser)
                if(count>0):
                    ratingInDb.rating = rat  # Set the desired updated value
                    ratingInDb.rated_date=timezone.now()
                    ratingInDb.save()
                    messages.warning(request,'You have already updated your review to'+' '+rat+' '+"star !!")
                    return render(request,'MovieRecommender/dashboard.html',params)
                action=Rating(user=u,movie=m,rating=rat)
                action.save()
                messages.success(request,'You have submitted'+' '+rat+' '+"star")
            return render(request,'MovieRecommender/dashboard.html',params)
        else:
            #print(request.user.id)
            rfm=AddRatingForm()
            params['rform']=rfm
            movie=Movie.objects.all()
            return render(request,'MovieRecommender/dashboard.html',params)
    else:
        return HttpResponseRedirect('/login/')
            
def user_logout(request):
    if request.user.is_authenticated:
        logout(request)
        return HttpResponseRedirect('/login/')


def profile(request):
    if request.user.is_authenticated:
        #"select sum(rating) from Rating where user=request.user.id"
        r=Rating.objects.filter(user=request.user.id)
        totalReview=0
        for item in r:
            totalReview+=int(item.rating)
        #select count(*) from Rating where user=request.user.id"
        totalwatchedmovie=Rating.objects.filter(user=request.user.id).count()
        return render(request,'MovieRecommender/profile.html',{'totalReview':totalReview,'totalwatchedmovie':totalwatchedmovie})
    else:
        return HttpResponseRedirect('/login/')


def movie_watched(request):
    userid = request.user.id
    u=User.objects.get(pk=userid)
    moviesOfUser = Rating.objects.filter(user=u)
    return moviesOfUser

project_demo_web_goi_y_phim/Movie-Recommendation-App/templates/MovieRecommender/addmovie.html
{% extends 'MovieRecommender/base.html' %}
{% block title %}Add Movie{% endblock title %}
{% block css %}
body{
    background: -webkit-linear-gradient(left, #3931af, #00c6ff);
}
{% endblock css %}
{%block content%}
 {%if perms.MovieRecommender.add_movie%}
<div class="container  mt-2 p-5 mb-2">
<h1 class="text-center text-light">Add Movie</h1>  
  <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for fm in form  %}
        <span class="text-light font-weight-bold">{{fm.label_tag}}</span>
        <p>{{fm}}</p>
        {% endfor %}
        <input type="submit" class="btn btn-primary" value="Add">
        </form><br>
        {% if messages %}
        {%for msg in messages%}
        {% if msg %}   <div class="alert alert-success">{{msg}}</div>{% endif %}
        {%endfor%}
        {% endif %}
</form>
</div>
{% else %}
<h1 class="text-light mt-2 ml-2">Only Admin has Permission To Add Movie</h1>
{% endif %}
{%endblock content%} 

project_demo_web_goi_y_phim/Movie-Recommendation-App/templates/MovieRecommender/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <title>{% block title %}  {% endblock title %}</title>
    <style>{% block css %} {% endblock css %}</style>
  </head>
  <body>
    {% include 'MovieRecommender/navbar.html' %}
                        {% block content %}



                        {% endblock content %}
      

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type="text/javascript">
      var currentButton;
      
      $(document).ready(function(){
        $(".toggleButton").on("click",function(e){
          var toggleButton = $(this);
          var yesButton = $("#yesButton");
          
          toggleButtonId = toggleButton.attr("id");
          console.log(toggleButtonId);
          console.log(currentButton);
          
          if (yesButton.hasClass(currentButton) && toggleButtonId == currentButton) {   
             
              var myDiv = toggleButton.next(".myDiv");
               myDiv.show();
           
            yesButton.removeClass(currentButton);
            
        } else{
          currentButton = toggleButton.attr("id");
          $("#confirmText").text("Have you watched this movie?");
          $("#confirmModal").modal();

        }

        });
        
        $("#yesButton").click(function() {
          var allMyDiv = $(".myDiv");
              allMyDiv.hide();
          var yesButton = $(this);
          yesButton.addClass(currentButton);
            });
        $("#noButton").click(function() {
            $(".myDiv").hide();
        });
        
      });
      
      
    </script>
  </body>
</html>

project_demo_web_goi_y_phim/Movie-Recommendation-App/templates/MovieRecommender/dashboard.html
{% extends 'MovieRecommender/base.html' %}
{% block title %}Dashboard{% endblock title %}
{% block css %}
body{
background: -webkit-linear-gradient(left, #3931af, #00c6ff);
}
.col-md-3
{
display: inline-block;
margin-left:-4px;
}

.carousel-indicators .active {
background-color: blue;
}

.col-md-3 img{

width: 170px;
height: 200px;
}

body .carousel-indicator li{
background-color: blue;
}

body .carousel-indicators{
bottom: 0;
}

body .carousel-control-prev-icon,
body .carousel-control-next-icon{
background-color: blue;
}

.carousel-control-prev,
.carousel-control-next{
top: auto;
bottom: auto;
padding-top: 222px;
}
body .no-padding{
padding-left: 0,
padding-right: 0;
}

.wrapper{

margin-bottom:200px;
}


{% endblock %}

{% block content %}
<div class="container wrapper">
  {% if messages %}
  {%for msg in messages%}
  {% if msg %} <div
    class="alert alert-{{msg.tags}} alert-dismissible fade show font-weight-bold text-primary w-50 ml-3 mt-5">{{msg}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button></div>{% endif %}
  {%endfor%}
  {% endif %}
 
  
  <!--Slideshow starts here -->
  {% for movie, range, nSlides in allMovies %}
  <h5 class="my-4 text-light"><u>{{movie.0.genres}} </u></h5>
  <div class="row">
    <div id="demo{{forloop.counter}}" class="col carousel slide my-3" data-ride="carousel">
      <ul class="carousel-indicators">
        <li data-target="#demo{{forloop.counter}}" data-slide-to="0" class="active"></li>

        {% for i in range %}
        <li data-target="#demo{{forloop.parentloop.counter}}" data-slide-to="{{i}}"></li>
        {% endfor %}
      </ul>


      <div class="container carousel-inner no-padding">

        <div class="carousel-item active">
          <div class="col-xs-3 col-sm-3 col-md-3">


            <div class="card" style="width: 18rem">
              <img class="card-img-top" src="../../static/default.jpg" alt="Card image cap" height="250px" width="200px">
              <div class="card-body">
                <h5 class="card-title">{{movie.0.title}}</h5>
                    {% for item in watchedMovie %}
                      {% if item.movie.id == movie.0.id %}
                        
                        <span>Your rate: {{ item.rating }}</span>
                      
                      {% endif %}
                    {% endfor %}
                
                <button class="toggleButton" id="{{movie.0.id}}">Rate it</button>
                <div class="myDiv" style="display: none;">
                  
                <form action="" method="post" class="range-field">
                  {% csrf_token %}
                  <input type="hidden" name="movieid" value="{{movie.0.id}}" />
                  <input type="hidden" name="userid" value="{{user.id}}" />
                  {{rform.as_p}}
                  <div class="showrating">

                  </div>
                  <input type="submit" class="btn btn-primary" value="Submit">
                </form>
              </div>
              </div>
              <div class="card-footer">
                <small class="text-muted">{{movie.0.genres}}</small>
                <small class="text-muted">{{movie.0.movieduration}}</small>
                <span class="text-muted">|{{movie.0.get_average_rating}} ({{movie.0.get_total_ratings}})</span>
              </div>
            </div>
          </div>


          {% for i in movie|slice:"1:"%}
          <div class="col-xs-3 col-sm-3 col-md-3">
            <div class="card" style="width: 18rem">
              <img class="card-img-top" src="../../static/default.jpg" alt="Card image cap" height="250px" width="200px">
              <div class="card-body">
                <h5 class="card-title">{{i.title}}</h5>
                {% for item in watchedMovie %}
                      {% if item.movie.id == i.id %}
                        
                        <span>Your rate: {{ item.rating }}</span>
                      
                      {% endif %}
                    {% endfor %}
                
                <button class="toggleButton"  id="{{i.id}}">Rate it</button>
                <div class="myDiv" style="display: none;">
                <form action="" method="post" class="range-field">
                  {% csrf_token %}
                  <input type="hidden" name="movieid" value="{{i.id}}" />
                  <input type="hidden" name="userid" value="{{user.id}}" />
                  {{rform.as_p}}
                  <div class="showrating">

                  </div>
                  
                  <input type="submit" class="btn btn-primary" value="Submit">
                </form>
              </div>
              </div>
              <div class="card-footer">
                <small class="text-muted">{{i.genres}}</small>
                <small class="text-muted">{{i.movieduration}}</small>
                <span class="text-muted">|{{i.get_average_rating}} ({{i.get_total_ratings}})</span>
              </div>
            </div>
          </div>
          {% if forloop.counter|divisibleby:4 and forloop.counter > 0 and not forloop.last %}
        </div>
        <div class="carousel-item">
          {% endif %}

          {% endfor %}
        </div>



      </div>
    </div>
    <!-- left and right controls for the slide -->
    <a class="carousel-control-prev" href="#demo{{forloop.counter}}" data-slide="prev">
      <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next" href="#demo{{forloop.counter}}" data-slide="next">
      <span class="carousel-control-next-icon"></span>
    </a>
  </div>
  {% endfor %}
</div>
<div class="container-fluid">
  <div class="modal fade text-center" id="confirmModal">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title" >Confirmation</h4>
					<button type="button" class="close" data-dismiss="modal">&times;</button>
				</div>
				
				<div class="modal-body">
					<span id="confirmText"></span>
				</div>
				
				<div class="modal-footer">
					<button class="btn btn-success" data-dismiss="modal" id="yesButton">Yes</button>
					<button type="button" class="btn btn-danger" data-dismiss="modal" id="noButton">No</button>
				</div>
			</div>
		</div>
	</div>
	
</div>
{% endblock %}

project_demo_web_goi_y_phim/Movie-Recommendation-App/templates/MovieRecommender/home.html
{% extends 'MovieRecommender/base.html' %}
{% block title %}Home{% endblock title %}
{% block css %}
body{
background: -webkit-linear-gradient(left, #3931af, #00c6ff);
}
.col-md-3
{
display: inline-block;
margin-left:-4px;
}

.carousel-indicators .active {
background-color: blue;
}

.col-md-3 img{

width: 170px;
height: 200px;
}

body .carousel-indicator li{
background-color: blue;
}

body .carousel-indicators{
bottom: 0;
}

body .carousel-control-prev-icon,
body .carousel-control-next-icon{
background-color: blue;
}

.carousel-control-prev,
.carousel-control-next{
top: auto;
bottom: auto;
padding-top: 222px;
}
body .no-padding{
padding-left: 0,
padding-right: 0;
}

.wrapper{

margin-bottom:200px;
}


{% endblock %}

{% block content %}
<div class="container wrapper">
  {% if recommended%}
  <h5 class="my-4 text-light">Recommended Movie For You</u></h5>
  <div class="row">
    {% for item in recommended %}
    <div class="col-4 mb-2">
      <div class="card" style="width: 18rem">
        <img class="card-img-top" src="../../static/default.jpg" alt="Card image cap" height="250px" width="200px">
        <div class="card-body">
          <h5 class="card-title">{{item.title}}</h5>
        </div>
        <div class="card-footer">
          <small class="text-muted">{{item.genres}}</small>
          <small class="text-muted">{{item.movieduration}}</small>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <h5 class="my-4 text-light">No Recommended Movie Found</u></h5>
  {% endif %}




  <br><br>
  <!--Slideshow starts here -->
  {% for movie, range, nSlides in allMovies %}

  <h5 class="my-4 text-light">Filtered By:{{movie.0.genres}}</h5>
  <div class="row">
    <div id="demo{{forloop.counter}}" class="col carousel slide my-3" data-ride="carousel">
      <ul class="carousel-indicators">
        <li data-target="#demo{{forloop.counter}}" data-slide-to="0" class="active"></li>

        {% for i in range %}
        <li data-target="#demo{{forloop.parentloop.counter}}" data-slide-to="{{i}}"></li>
        {% endfor %}
      </ul>


      <div class="container carousel-inner no-padding">

        <div class="carousel-item active">
          <div class="col-xs-3 col-sm-3 col-md-3">


            <div class="card" style="width: 18rem">
              <img class="card-img-top" src="../../static/default.jpg" alt="Card image cap" height="250px" width="200px">
              <div class="card-body">
                <h5 class="card-title">{{movie.0.title}}</h5>
              </div>
              <div class="card-footer">
                <small class="text-muted">{{movie.0.genres}}</small>
                <small class="text-muted">{{movie.0.movieduration}}</small>
              </div>
            </div>
          </div>


          {% for i in movie|slice:"1:"%}
          <div class="col-xs-3 col-sm-3 col-md-3">
            <div class="card" style="width: 18rem">
              <img class="card-img-top" src="../../static/default.jpg" alt="Card image cap" height="250px" width="200px">
              <div class="card-body">
                <h5 class="card-title">{{i.title}}</h5>
              </div>
              <div class="card-footer">
                <small class="text-muted">{{i.genres}}</small>
                <small class="text-muted">{{i.movieduration}}</small>
              </div>
            </div>
          </div>
          {% if forloop.counter|divisibleby:4 and forloop.counter > 0 and not forloop.last %}
        </div>
        <div class="carousel-item">
          {% endif %}

          {% endfor %}
        </div>



      </div>
    </div>
    <!-- left and right controls for the slide -->
    <a class="carousel-control-prev" href="#demo{{forloop.counter}}" data-slide="prev">
      <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next" href="#demo{{forloop.counter}}" data-slide="next">
      <span class="carousel-control-next-icon"></span>
    </a>
  </div>
  {% endfor %}
</div>
{% endblock %}

project_demo_web_goi_y_phim/Movie-Recommendation-App/templates/MovieRecommender/login.html
{% extends 'MovieRecommender/base.html' %}
{% block title %}Login{% endblock title %}
{% block css %}
body{
    background: -webkit-linear-gradient(left, #3931af, #00c6ff);
}
{% endblock css %}
{% block content %}
<div class="container p-5 mb-5">
<form action="" method="post" novalidate>
{% csrf_token %}
{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<div class="alert alert-danger">{{error}}</div>
{% endfor %}
{% endif %} <br>
{% for fm in  form %}
<span class="text-light">{{fm.label_tag}}</span>
<p>
{{fm}}
</p>
{% if fm.errors  %}
<div class="alert alert-danger">
{{fm.errors|striptags}}
</div>
{% endif %}
{% endfor %} <br>
<input type="submit" value="Login" class="btn btn-primary"><br>
</form>
</div>
{% endblock content %}